server:
  port: 9001
  
spring:
  application:
    name: university-service
    
eureka:
  client:
    register-with-eureka: true
    
    service-url:
        default-zone: http://localhost:8761/eureka/
    instance:
        hostname: localhost    
        
hystrix:
  command: 
    fallbackcmd:
      execution:
        isolation: 
          thread: 
            timeoutInMilliseconds: 5000 
      